/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Location
 */

public class Timezone {
  public static final String SERIALIZED_NAME_SHORT_NAME = "short_name";
  @SerializedName(SERIALIZED_NAME_SHORT_NAME)
  private String shortName;

  public static final String SERIALIZED_NAME_OFFSET_SEC = "offset_sec";
  @SerializedName(SERIALIZED_NAME_OFFSET_SEC)
  private int offsetSec;

  public static final String SERIALIZED_NAME_NOW_IN_DST = "now_in_dst";
  @SerializedName(SERIALIZED_NAME_NOW_IN_DST)
  private int nowInDST;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public Timezone shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public Timezone offsetSec(int offsetSec) {
    this.offsetSec = offsetSec;
    return this;
  }

   /**
   * Get offsetSec
   * @return offsetSec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public int getOffsetSec() {
    return offsetSec;
  }

  public void setOffsetSec(int offsetSec) {
    this.offsetSec = offsetSec;
  }

  public Timezone nowInDST(int nowInDST) {
    this.nowInDST = nowInDST;
    return this;
  }

   /**
   * Get nowInDST
   * @return nowInDST
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public int getNowInDST() {
    return nowInDST;
  }

  public void setNowInDST(int nowInDST) {
    this.nowInDST = nowInDST;
  }

  public Timezone name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get osmType
   * @return osmType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Timezone location = (Timezone) o;
    return Objects.equals(this.shortName, location.shortName) &&
        Objects.equals(this.offsetSec, location.offsetSec) &&
        Objects.equals(this.nowInDST, location.nowInDST) &&
        Objects.equals(this.name, location.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shortName, offsetSec, nowInDST, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Timezone {\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    offsetSec: ").append(toIndentedString(offsetSec)).append("\n");
    sb.append("    nowInDST: ").append(toIndentedString(nowInDST)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
