/*
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.locationiq.client.model;

import org.junit.Test;


/**
 * Model tests for DirectionsNearest
 */
public class DirectionsNearestTest {
    private final DirectionsNearest model = new DirectionsNearest();

    /**
     * Model tests for DirectionsNearest
     */
    @Test
    public void testDirectionsNearest() {
        // TODO: test DirectionsNearest
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'waypoints'
     */
    @Test
    public void waypointsTest() {
        // TODO: test waypoints
    }

}
